image: ghcr.io/astral-sh/uv:python3.13-bookworm

stages:
  - code quality
  - test
  - deploy

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

cache:
  paths:
    - .cache/uv

before_script:
  - python --version
  - uv --version

code_quality:
  stage: code quality
  script:
    - uv sync
    - uv run ruff check .

test:
  stage: test
  script:
    - uv sync --extra test
    - uv run pytest -q

run:
  script:
    - uv build
  artifacts:
    paths:
      - dist/*

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
