image: ghcr.io/astral-sh/uv:python3.13-bookworm

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

cache:
  paths:
    - .cache/uv

before_script:
  - python --version
  - uv --version

test:
  script:
    - uv sync --extra test
    - uv run tox -e py,ruff

run:
  script:
    - uv build
  artifacts:
    paths:
      - dist/*

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
