[project]
name = "warehouse-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charles Hayes", email = "cfhayes16@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.16.4",
]

[project.scripts]
warehouse-demo = "warehouse_demo:main"

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "tox>=4.0",
]

[tool.tox]
env_list = ["py", "ruff"]
requires = ["tox>=4.0"]

[tool.tox.env_run_base]
package = "editable"
deps = [
    "pytest>=8.0",
]
commands = [["python", "-m", "pytest"]]

[tool.tox.env.ruff]
deps = [
    "ruff>=0.16.4",
]
commands = [["ruff", "check", "."]]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
